name: Verify NPM Access Token

on:
  workflow_call:
    inputs:
      registry:
        type: string
        description: The URL of the NPM package registry to verify the authentication for
        default: https://registry.npmjs.org
    secrets:
      npmToken:
        description: The Personal Access Token for authenticating to the NPM package repository
        required: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: ${{ inputs.registry }}
      - name: Verify NPM Access Token
        run: npm whoami || { echo "The NPM Access Token is invalid!" && false; }
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npmToken }}
